/*
 * DIO_config.h
 *
 *  Created on: Dec 6, 2023
 *      Author: engah
 */

#ifndef DIO_CONFIG_H_
#define DIO_CONFIG_H_

/*
 * PORT DIRCTIONS
 * OPTIONS:
 * 			1- DIO_u8OUTPUT
 * 			2- DIO_u8INPUT
 * */
#define PORTA_PIN0_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN1_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN2_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN3_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN4_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN5_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN6_DIRECTION		DIO_u8OUTPUT
#define PORTA_PIN7_DIRECTION		DIO_u8OUTPUT


#define PORTB_PIN0_DIRECTION		DIO_u8INPUT
#define PORTB_PIN1_DIRECTION		DIO_u8INPUT
#define PORTB_PIN2_DIRECTION		DIO_u8INPUT
#define PORTB_PIN3_DIRECTION		DIO_u8INPUT
#define PORTB_PIN4_DIRECTION		DIO_u8INPUT
#define PORTB_PIN5_DIRECTION		DIO_u8INPUT
#define PORTB_PIN6_DIRECTION		DIO_u8INPUT
#define PORTB_PIN7_DIRECTION		DIO_u8INPUT


#define PORTC_PIN0_DIRECTION		DIO_u8OUTPUT
#define PORTC_PIN1_DIRECTION		DIO_u8OUTPUT
#define PORTC_PIN2_DIRECTION		DIO_u8OUTPUT
#define PORTC_PIN3_DIRECTION		DIO_u8INPUT
#define PORTC_PIN4_DIRECTION		DIO_u8INPUT
#define PORTC_PIN5_DIRECTION		DIO_u8INPUT
#define PORTC_PIN6_DIRECTION		DIO_u8INPUT
#define PORTC_PIN7_DIRECTION		DIO_u8INPUT


#define PORTD_PIN0_DIRECTION		DIO_u8OUTPUT
#define PORTD_PIN1_DIRECTION		DIO_u8OUTPUT
#define PORTD_PIN2_DIRECTION		DIO_u8OUTPUT
#define PORTD_PIN3_DIRECTION		DIO_u8OUTPUT
#define PORTD_PIN4_DIRECTION		DIO_u8INPUT
#define PORTD_PIN5_DIRECTION		DIO_u8INPUT
#define PORTD_PIN6_DIRECTION		DIO_u8INPUT
#define PORTD_PIN7_DIRECTION		DIO_u8INPUT


/*
 * PORT INTIAL VALUE
 * OPTIONS:
 * 			1- DIO_u8HIGH
 * 			2- DIO_u8LOW
 * */
#define PORTA_PIN0_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN1_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN2_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN3_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN4_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN5_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN6_INIT_VALUE		DIO_u8LOW
#define PORTA_PIN7_INIT_VALUE		DIO_u8LOW


#define PORTB_PIN0_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN1_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN2_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN3_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN4_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN5_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN6_INIT_VALUE		DIO_u8LOW
#define PORTB_PIN7_INIT_VALUE		DIO_u8LOW


#define PORTC_PIN0_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN1_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN2_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN3_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN4_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN5_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN6_INIT_VALUE		DIO_u8LOW
#define PORTC_PIN7_INIT_VALUE		DIO_u8LOW


#define PORTD_PIN0_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN1_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN2_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN3_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN4_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN5_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN6_INIT_VALUE		DIO_u8LOW
#define PORTD_PIN7_INIT_VALUE		DIO_u8LOW


#endif /* DIO_CONFIG_H_ */
